export default {
  FondoSeccin: {
    padding: "32px 58px 66px 54px;",
    backgroundColor: "#f5f5f7",
  },
  title: {
    fontSize: 28,
    opacity: 0.87,
    fontWeight: 700,
    color: "#2d2d37",
  },
  appText: {
    fontSize: 9,
    color: "#2979ff",
    position: "relative",
    bottom: 17,
    right: 5,
  },
  link: {
    color: "#1a70ff",
    fontWeight: 500,
    fontSize: 14,
  },
  footer: {
    width: "100%",
    textAlign: "center",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: 1.21,
    letterSpacing: 0.02,
    color: "#797979",
  },
  button: {
    borderColor: "#e1e2e6",
    backgroundColor: "#2979ff",
    color: "#fff",
  },
  card: {
    width: 430,
    textAlign: "center",
    borderRadius: 16,
    borderStyle: "none",
    paddingRight: 30,
    paddingLeft: 30,
    paddingTop: 5,
    paddingBottom: 20,
  },
  input: {
    marginTop: 18,
    marginBottom: 26,
    // width: 364,
    height: 54,
    borderRadius: 6,
  },
};
